- name: inastall ngnix and start service
  hosts: web
  become: yes # this is equal to get root access
  tasks: 
  - name: installing ngnix
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: start and enable ngnix
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
