- name: Assigning variables using prompt
  hosts: localhost
  vars_prompt:
    - name: USERNAME
      prompt: please enter username
      private: false #visible or not while entering
    - name: PASSWORD
      prompt: please enter password
      private: false #visible or not while entering
  tasks:
  - name: Verfing the prompt variables
    ansible.builtin.debug:
      msg: "Please enter username: {{USERNAME}} password: {{PASSWORD}}"